name: eidetics_env
channels:
  - defaults
dependencies:
  - python=3.8
  - flask=1.1.2
  - flask-sqlalchemy=2.4.4
  - flask-mail=0.9.1
  - sqlalchemy=1.3.23  # Specify a compatible version of SQLAlchemy
  - pip
  - pip:
    - google-cloud-storage==1.36.2
    - openai==0.10.2
    - celery==5.0.5
    - itsdangerous==1.1.0
    - redis
    - Flask-Migrate==3.1.0
